// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("rescript/lib/js/caml_int32.js");

var toEmptyChar = /[.,\/#!$%\^;:{}=\-_`~()]/g;

var toSpace = /[\s\u00A0\n]/g;

var emptyChar = "";

var space = " ";

function isNotEmpty(val) {
  return val !== emptyChar;
}

function getReadingData(readingSpeedOpt, text) {
  var readingSpeed = readingSpeedOpt !== undefined ? readingSpeedOpt : 200;
  var numOfWords = text.replace(toEmptyChar, emptyChar).replace(toSpace, space).split(space).filter(isNotEmpty).length;
  return {
          readingTime: Caml_int32.div(numOfWords, readingSpeed),
          numOfWords: numOfWords
        };
}

var Recount_readingSpeed = {
  slow: 200,
  relaxed: 230,
  moderate: 260,
  fast: 290,
  lightSpeed: 320,
  ludicrousSpeed: 350
};

var Recount = {
  readingSpeed: Recount_readingSpeed,
  toEmptyChar: toEmptyChar,
  toSpace: toSpace,
  emptyChar: emptyChar,
  space: space,
  isNotEmpty: isNotEmpty,
  getReadingData: getReadingData
};

exports.Recount = Recount;
/* No side effect */
